In [3]:
from pandas import read_csv
path="/home/admin1/Desktop/iris.csv"

In [4]:
data=read_csv(path)
print(data.shape)

(150, 6)


In [5]:
print(data)

     sepal_length  sepal_width  petal_length  petal_width    species category
0             5.1          3.5           1.4          0.2     setosa        B
1             4.9          3.0           1.4          0.2     setosa        B
2             4.7          3.2           1.3          0.2     setosa        B
3             4.6          3.1           1.5          0.2     setosa        B
4             5.0          3.6           1.4          0.2     setosa        B
5             5.4          3.9           1.7          0.4     setosa        B
6             4.6          3.4           1.4          0.3     setosa        B
7             5.0          3.4           1.5          0.2     setosa        B
8             4.4          2.9           1.4          0.2     setosa        B
9             4.9          3.1           1.5          0.1     setosa        B
10            5.4          3.7           1.5          0.2     setosa        B
11            4.8          3.4           1.6          0.2     se

In [7]:
print(data[:3])

   sepal_length  sepal_width  petal_length  petal_width species category
0           5.1          3.5           1.4          0.2  setosa        B
1           4.9          3.0           1.4          0.2  setosa        B
2           4.7          3.2           1.3          0.2  setosa        B


In [8]:
print(data.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [10]:
count_class=data.groupby('species').size()
print(count_class)

species
setosa        50
versicolor    50
virginica     50
dtype: int64


In [11]:
correlatiions=data.corr(method='pearson')
print(correlatiions)

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000


In [13]:
print(data.skew())

sepal_length    0.314911
sepal_width     0.318966
petal_length   -0.274884
petal_width    -0.102967
dtype: float64


In [15]:
from sklearn import preprocessing
array=data.iloc[:,0:4].values
print(array)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.2]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.6  1.4  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [21]:
data_scalar=preprocessing.MinMaxScaler(feature_range=(0,1))
adat_resclar=data_scalar.fit_transform(array)

In [23]:
print(adat_resclar)

[[ 0.22222222  0.625       0.06779661  0.04166667]
 [ 0.16666667  0.41666667  0.06779661  0.04166667]
 [ 0.11111111  0.5         0.05084746  0.04166667]
 [ 0.08333333  0.45833333  0.08474576  0.04166667]
 [ 0.19444444  0.66666667  0.06779661  0.04166667]
 [ 0.30555556  0.79166667  0.11864407  0.125     ]
 [ 0.08333333  0.58333333  0.06779661  0.08333333]
 [ 0.19444444  0.58333333  0.08474576  0.04166667]
 [ 0.02777778  0.375       0.06779661  0.04166667]
 [ 0.16666667  0.45833333  0.08474576  0.        ]
 [ 0.30555556  0.70833333  0.08474576  0.04166667]
 [ 0.13888889  0.58333333  0.10169492  0.04166667]
 [ 0.13888889  0.41666667  0.06779661  0.        ]
 [ 0.          0.41666667  0.01694915  0.        ]
 [ 0.41666667  0.83333333  0.03389831  0.04166667]
 [ 0.38888889  1.          0.08474576  0.125     ]
 [ 0.30555556  0.79166667  0.05084746  0.125     ]
 [ 0.22222222  0.625       0.06779661  0.08333333]
 [ 0.38888889  0.75        0.11864407  0.08333333]
 [ 0.22222222  0.75        0.08

In [35]:
from sklearn.preprocessing import Binarizer
binarizer=Binarizer(threshold=0.5).fit(array)
dataa_bin=binarizer.transform(array)
print(dataa_bin[0:5])

[[ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  0.]]


In [36]:
from sklearn.preprocessing import StandardScaler
import numpy as np
#data=np.array([[0,0],[1,0],[0,1],[1,1]])
D=StandardScaler().fit(array)
D_rescaled=D.transform(array)
print(D_rescaled)

[[ -9.00681170e-01   1.01900435e+00  -1.34022653e+00  -1.31544430e+00]
 [ -1.14301691e+00  -1.31979479e-01  -1.34022653e+00  -1.31544430e+00]
 [ -1.38535265e+00   3.28414053e-01  -1.39706395e+00  -1.31544430e+00]
 [ -1.50652052e+00   9.82172869e-02  -1.28338910e+00  -1.31544430e+00]
 [ -1.02184904e+00   1.24920112e+00  -1.34022653e+00  -1.31544430e+00]
 [ -5.37177559e-01   1.93979142e+00  -1.16971425e+00  -1.05217993e+00]
 [ -1.50652052e+00   7.88807586e-01  -1.34022653e+00  -1.18381211e+00]
 [ -1.02184904e+00   7.88807586e-01  -1.28338910e+00  -1.31544430e+00]
 [ -1.74885626e+00  -3.62176246e-01  -1.34022653e+00  -1.31544430e+00]
 [ -1.14301691e+00   9.82172869e-02  -1.28338910e+00  -1.44707648e+00]
 [ -5.37177559e-01   1.47939788e+00  -1.28338910e+00  -1.31544430e+00]
 [ -1.26418478e+00   7.88807586e-01  -1.22655167e+00  -1.31544430e+00]
 [ -1.26418478e+00  -1.31979479e-01  -1.34022653e+00  -1.44707648e+00]
 [ -1.87002413e+00  -1.31979479e-01  -1.51073881e+00  -1.44707648e+00]
 [ -5.

In [37]:
from numpy import set_printoptions
set_printoptions(precision=2)
print(D_rescaled[0:5])

[[-0.9   1.02 -1.34 -1.32]
 [-1.14 -0.13 -1.34 -1.32]
 [-1.39  0.33 -1.4  -1.32]
 [-1.51  0.1  -1.28 -1.32]
 [-1.02  1.25 -1.34 -1.32]]


In [7]:
from sklearn import preprocessing
import numpy as np
y=data.iloc[:4].values
print(y)
encoder=preprocessing.LabelEncoder()
a=encoder.fit(y)
print(a)
LabelEncoder()
dec_list=encoder.inverse_transform(encoded_values)

NameError: name 'data' is not defined

In [18]:
from sklearn.preprocessing import Imputer
data=np.array([[1,np.nan,2],[2,3,np.nan],[-1,4,2]])
data

In [19]:
imp=Imputer(strategy='mean')

In [22]:
array=imp.fit_transform(data)

In [23]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
fit=pca.fit(array)
print(fit.explained_variance_ratio_)
print(fit.components_)

[ 0.99686845  0.00313155]
[[-0.95171801  0.30697366 -0.        ]
 [ 0.30697366  0.95171801  0.        ]]
